[package]
name = "ring-buffer"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
minstant = "0.1"

[profile.test]
opt-level = 3
debug = false
strip = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false
